# ===== H2 File-based Database =====
spring.datasource.url=jdbc:h2:file:./data/requestdb;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===== H2 Console (development only) =====
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===== JPA / Hibernate =====
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== Vaadin =====
vaadin.launch-browser=true

# ===== Auto-load data.sql after schema generation =====
spring.sql.init.mode=never
spring.sql.init.continue-on-error=true
spring.jpa.defer-datasource-initialization=true


# ===== Upload Limits =====
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# ===== Mail Server Configuration =====
# To send real emails, replace 'localhost' with your SMTP server (e.g., smtp.gmail.com)
# and provide your email and password.
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bozkurtsila06@gmail.com
spring.mail.password=eiacrzedvgmcmhop
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

