
DROP TABLE workflows_Sila CASCADE CONSTRAINTS;
DROP TABLE priorities_Sila CASCADE CONSTRAINTS;
DROP TABLE requests_Sila CASCADE CONSTRAINTS;
DROP TABLE users_Sila CASCADE CONSTRAINTS;
DROP TABLE company_Sila CASCADE CONSTRAINTS;

CREATE TABLE company_Sila(
    company_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR2(100) NOT NULL,
    company_points NUMBER
);
/*
HER userda bulunan �zellikler:
- name and surname
- email
- password
- ID
- company ID

Adminde bulunan �zellikler:
- her user a ve page e m�dahale yetkisi (b�t�n tablolara eri�me ve m�dahale etme)
- b�t�n userlar (o tabloya eri�im)
- b�t�n requestler ( o tabloya eri�im)

Customerda bulunan �zellikler: sadece IT departman�ndan geldi�i i�in �nceli�e �r�n ve yaz�l�m ba�kanlar� bakacak
- ge�mi�te submit edilmi� b�t�n requestler liste olarak
- bu tasklar� g�r�nt�leme ve editleme yetkisi ama sadece kendi submit etti�i requestler bunlar� g�ncelleyebilir

Yaz�l�m Y�neticisinde bulunan �zellikler:
- gelen requestlerin �ncelik puanlar�na etki edecek olan baz� noktalar� belirler
- requestlere bakacak olan yaz�l�mc�ya o request i atama
- g�ncelleme gelen requestleri d�zenleme/g�rme
- ge�mi� requestleri g�r�nt�leme

�r�n Y�neticisinde bulunan �zellikler:
- gelen requestlerin �ncelik puanlar�na etki edecek olan baz� noktalar� belirler
- g�ncelleme gelen requestleri d�zenleme/g�rme
-ge�mi� requestleri g�r�nt�leme

Yaz�l�mc�da bulunan �zellikler:
- gelen requestleri onaylama ya da supervisor a geri g�nderme
- gelen requestleri tamamland�/tamamlanmad�/�zerinde �al���yor olarak i�aretlemek

*/

CREATE TABLE users_Sila(
       user_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       name_surname VARCHAR2(50) NOT NULL,
       email VARCHAR2(100) NOT NULL UNIQUE,
       role VARCHAR2(20) NOT NULL,
       password VARCHAR2(50) NOT NULL,
       company_ID NUMBER(8) NOT NULL,
       
       CONSTRAINT chk_user_role CHECK (role IN ('ADMIN','YAZILIMCI','MUSTERI','URUN_SORUMLUSU','YAZILIM_YONETICISI')),
       CONSTRAINT fk_company_ID FOREIGN KEY(company_ID) REFERENCES company_Sila(company_ID)
);

/*

REQUESTLERIN �ZELL�KLER�
- creator_ID 
- request_ID
- title
- description
- status (APPROVED/ PENDING/ DONE/REJECTED)
- company points (al�nan paraya g�re)
- customer rank(her request IT'den geliyor ama bu gelen requestlerin geldi�i nokta �r�n y�netici tarafondan denetlenerek �nceliklendirilebilir.)
- �r�n de�erlendirmesi �ncelik puan� 1-5
- yaz�l�m y�netici �ncelik puan� 1-5
- �deme durumu �nceli�i
(tabloda yok ama �ncelik hesab�nda o companynin isteklerinin tamamlanma y�zdeside var)
- �ncelik puan�
- atanan yaz�l�mc�_ID

*/

CREATE TABLE requests_Sila (
    request_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_ID NUMBER NOT NULL,
    title VARCHAR2(255) NOT NULL,
    description VARCHAR2(4000) NOT NULL,
    
    status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    final_priority_score NUMBER(10, 2), 
    
    CONSTRAINT chk_status CHECK (status IN ('APPROVED', 'PENDING', 'DONE', 'REJECTED', 'IN_PROGRESS')),
    CONSTRAINT fk_req_creator FOREIGN KEY (creator_ID) REFERENCES users_Sila(user_ID)
);

CREATE TABLE priorities_Sila(
    priority_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_ID NUMBER NOT NULL,
    company_points NUMBER (10,2),
    customer_rank NUMBER,
    product_mgr_score NUMBER,
    software_mgr_score NUMBER,
    payment_priority NUMBER,
    priority_score NUMBER (10,2),
    CONSTRAINT chk_product_score CHECK (product_mgr_score BETWEEN 1 AND 5),
    CONSTRAINT chk_software_score CHECK (software_mgr_score BETWEEN 1 AND 5),
    CONSTRAINT chk_request_ID FOREIGN KEY (request_ID) REFERENCES requests_Sila(request_ID)
);

CREATE TABLE workflows_Sila(
    task_ID NUMBER(8),
    request_ID NUMBER,
    developer_ID NUMBER,
    workflow_status VARCHAR2(20) DEFAULT 'UNASSIGNED' NOT NULL,

    CONSTRAINT fk_req_developer FOREIGN KEY (developer_ID) REFERENCES users_Sila(user_ID),
    CONSTRAINT fk_wf_request_id FOREIGN KEY (request_ID) REFERENCES requests_Sila(request_ID),
    CONSTRAINT chk_workflow_status CHECK (workflow_status IN ('ASSIGNED', 'UNASSIGNED', 'RESOLVED', 'RESENT'))
);

